from .animals import Animal
from .alpaca import Alpaca
from .cobra import Cobra
from .copperhead import CopperHead
from .deer import Deer
from .dolphin import Dolphin
from .goat import Goat
from .koifish import KoiFish
from .lionfish import LionFish
from .llama import Llama
from .otter import Otter
from .salamander import Salamander
from .shark import Shark
from .snake import Snake
from .watersnake import WaterSnake
from .wolf import Wolf